"""
ssl_builder.py — Build an SSLContextContainer for mTLS connections.

Exposes one public function:
  build_ssl_container(logger) -> SSLContextContainer

Certificate candidates are tried in priority order:
  1. Qt/certs_out/   — generated by Qt/gen_certs.py (preferred)
  2. pat/certs/      — IHE PAT test PKI
  3. tests/certs/    — sdc11073 unit-test PKI (last resort)
"""

import ssl
import logging
import pathlib
from typing import Any


def build_ssl_container(logger: logging.Logger) -> Any:
    """
    Build and return an SSLContextContainer with a loaded client certificate.

    Two SSL contexts are created:
      client_context — used for outgoing HTTPS requests (consumer → provider)
      server_context — used for incoming WS-Eventing notifications (provider → consumer)
        NOTE: PROTOCOL_TLS_SERVER is mandatory here; create_default_context()
        returns a CLIENT context that cannot accept incoming TLS connections.

    Both contexts have hostname verification and peer certificate validation
    disabled (CERT_NONE) because SDC devices typically use self-signed certs.

    Returns:
      certloader.SSLContextContainer on success.
      Falls back gracefully if no certificate file is found (logs a warning).
    """
    _qt_dir = pathlib.Path(__file__).parent.parent   # Master/Qt/
    _base   = _qt_dir.parent                          # Master/

    _cert_candidates = [
        # (cert_file, key_file, ca_file, [passwords])
        (_qt_dir / 'certs_out' / 'consumer.pem',
         _qt_dir / 'certs_out' / 'consumer.key',
         _qt_dir / 'certs_out' / 'ca1.pem',
         [None]),
        (_qt_dir / 'certs_out' / 'consumer.pem',
         _qt_dir / 'certs_out' / 'consumer.key',
         _qt_dir / 'certs_out' / 'ca.pem',
         [None]),
        (_base / 'pat' / 'certs' / 'consumer.pem',
         _base / 'pat' / 'certs' / 'consumer.key',
         _base / 'pat' / 'certs' / 'ca1.pem',
         [None]),
        (_base / 'pat' / 'certs' / 'user_certificate_root_signed.pem',
         _base / 'pat' / 'certs' / 'user_private_key_encrypted.pem',
         _base / 'pat' / 'certs' / 'root_certificate.pem',
         ['dummypassword', 'password', 'sdcX', '12345']),
        (_base / 'tests' / 'certificates' / 'test_certificate.pem',
         _base / 'tests' / 'certificates' / 'test_private_key.pem',
         None,
         ['password', 'dummypassword']),
    ]

    # Consumer → provider (standard TLS client)
    client_ctx = ssl.create_default_context()
    client_ctx.check_hostname = False
    client_ctx.verify_mode = ssl.CERT_NONE

    # Provider → consumer (WS-Eventing push notifications — must be a SERVER context)
    server_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    server_ctx.check_hostname = False
    server_ctx.verify_mode = ssl.CERT_NONE

    loaded = False
    for cert_file, key_file, ca_file, passwords in _cert_candidates:
        if not (cert_file.exists() and key_file.exists()):
            continue
        for pwd in passwords:
            try:
                kw: dict = dict(certfile=str(cert_file), keyfile=str(key_file), password=pwd or None)
                client_ctx.load_cert_chain(**kw)
                server_ctx.load_cert_chain(**kw)
                if ca_file and ca_file.exists():
                    client_ctx.load_verify_locations(cafile=str(ca_file))
                    server_ctx.load_verify_locations(cafile=str(ca_file))
                logger.info(
                    f'mTLS: cert loaded from {cert_file.parent} '
                    f"(password={'<empty>' if not pwd else repr(pwd)})"
                )
                loaded = True
                break
            except Exception:
                continue
        if loaded:
            break

    if not loaded:
        logger.warning(
            'Could not load any client cert. '
            'Attempting TLS without client certificate (mTLS will fail if required).'
        )

    from sdc11073 import certloader
    return certloader.SSLContextContainer(
        client_context=client_ctx,
        server_context=server_ctx,
    )

